### ISSUE TITLE
[ASP]Rechnungen werden u.U. nicht angezeigt

### ISSUE THREAD

**Issue by dowe** [dowe/Project2#5]
Wird die DB neu erzeugt und der Server wird gestartet, wenn schon Rechnungen vorhanden sind so werden diese nicht angezeigt, da der Pfad nur bei neuerzeugten Rechnungen in die DB geschrieben wird.

Lösungsvorschläge:
- Bei DB Init alle PDFs löschen
- Bei Server Start alle schon vorhandenen PDF erneut in DB schreiben, falls sie noch nicht vorhanden sind.

Was wäre am Besten?

**Comment by Tiiinky** [comment]
Alle löschen is auf jedenfall einfacher und sauberer. Oder sieht jemand ein
Problem?
Am 04.06.2015 15:02 schrieb "dowe" notifications@github.com:
